### ISSUE TITLE
Does it support both gcr and gar?

### ISSUE THREAD

**Issue by billchen8888** [kameshsampath/drone-google-cloud-auth#2]
Hi, Kamesh,

Tis is a great plugin!

Does this one support both GCR and GAR ? When I set the GAR repo uri, somehow I get WARNING saying "not a supported registry".

Thanks.

-Bill

**Comment by kameshsampath** [comment]
Hi @billchen8888 , I have not tested that with GAR as I never used it. But I try to see if I can add support for it. Just for my clarity you want support for GAR == [Google Artifact Repository?](https://cloud.google.com/artifact-registry)

**Comment by billchen8888** [comment]
Thanks.  Correct.  Google made a statement that  the GCR will be replaced by  GAR (google artifact repository)

**Comment by kameshsampath** [comment]
@billchen8888  I have fixed it used GAR now and you can use the plugin image `kameshsampath/drone-gcloud-auth:2.0.0` and it now defaults to GAR and I have deprecated the use of `Container Registry`. It should be merged into the official plugin  index soon. 

PS:  Check the parameter name changes
